### ISSUE TITLE
logout doesn't seem to get rid of my session

### ISSUE THREAD

**Issue by vmutti** [JoshuaKGoldberg/Bookswap#123]

**Comment by JoshuaKGoldberg** [comment]
WELL THAT'S UNFORTUNATE LOL

**Comment by jcamino** [comment]
O?

**Comment by jcamino** [comment]
Did you actually fix it?

**Comment by jcamino** [comment]
O??

**Comment by vmutti** [comment]
to be clear:
I log in with facebook
I click log out
this logs me out of facebook but my bookswap session stays open

**Comment by JoshuaKGoldberg** [comment]
Imagine the number of stars in the sky...

Imagine the number of grains of sand on the beach...

That's how many craps I don't give about this issue anymore. Unsubsribed.
