### ISSUE TITLE
Mobile layout

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/Bookswap#14]
soz Javier...

The site is already almost mobile-friendly, but the CSS should be made to be relative. Very few @media CSS queries should be necessary (but more em measurements for sure).

**Comment by jcamino** [comment]
why soz?

**Comment by JoshuaKGoldberg** [comment]
You brought this up a very, very long time ago.

**Comment by JoshuaKGoldberg** [comment]
Generally fixed. Close enough!
