### ISSUE TITLE
website is vulnerable to NULL byte attacks.

### ISSUE THREAD

**Issue by aidielse** [JoshuaKGoldberg/Bookswap#27]
can execute arbitrary code by typing code into any input box.

e.x.

I can type: %00<script>alert(1)</script> into the search RPI Bookswap page.

**Comment by aidielse** [comment]
![screen shot 2014-01-31 at 9 36 18 pm](https://f.cloud.github.com/assets/5459264/2056708/b2949556-8ae9-11e3-825a-390a195d9acf.png)

**Comment by JoshuaKGoldberg** [comment]
Less severe version of https://github.com/Diogenesthecynic/Bookswap/issues/29.
