### ISSUE TITLE
Users can't remove books that another user is selling/is buying, but the page makes it look like they can.

### ISSUE THREAD

**Issue by aidielse** [JoshuaKGoldberg/Bookswap#28]
If i navigate to the homepage of another user, I can click the X next to books that they are buying/selling and the page will display as if I removed them. This option should be removed all together if a user is visiting a different user's homepage.

**Comment by JoshuaKGoldberg** [comment]
Should be fixed in https://github.com/Diogenesthecynic/Bookswap/commit/68f80bcbb51d19f281b9fdd01cb59bae8147c9e2.
