### ISSUE TITLE
Users can execute arbitrary client side code

### ISSUE THREAD

**Issue by aidielse** [JoshuaKGoldberg/Bookswap#29]
Don't even need to utilize a null byte to execute scripts and stuff.

**Comment by JoshuaKGoldberg** [comment]
More severe version of https://github.com/Diogenesthecynic/Bookswap/issues/27.

**Comment by JoshuaKGoldberg** [comment]
Fixed in https://github.com/Diogenesthecynic/Bookswap/commit/6e70ada9d88615cfd472f993eb5d47f53cd4f27a.
