### ISSUE TITLE
Install page suggests incorrect getBase() location

### ISSUE THREAD

**Issue by harish** [JoshuaKGoldberg/Bookswap#33]
Specifies path to install.php instead of just the containing directory

**Comment by jcamino** [comment]
Not for me. Did this get fixed? I'm on OS X.

![screenshot 2014-02-09 14 00 17](https://f.cloud.github.com/assets/892117/2120608/8ad16fd8-91bc-11e3-84a1-961b29ee84ae.png)

**Comment by JoshuaKGoldberg** [comment]
This appears to be fixed in the latest version.
