### ISSUE TITLE
Internal Server Error when making API request

### ISSUE THREAD

**Issue by harish** [JoshuaKGoldberg/Bookswap#39]
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)" when searching Google Books API from import page. 

Apache log: [Mon Feb 03 15:42:55 2014] [error] [client 127.0.0.1] PHP Fatal error:  Call to undefined function curl_init() in /var/www/Bookswap/settings.php on line 131, referer: http://localhost/Bookswap/index.php?page=import

install.php should require cURL library.

**Comment by JoshuaKGoldberg** [comment]
Checked for in https://github.com/Diogenesthecynic/Bookswap/commit/254538118864ad59df30c40f31cddfa1e9cfcbce
