### ISSUE TITLE
Passwords are incredibly insecure.

### ISSUE THREAD

**Issue by aidielse** [JoshuaKGoldberg/Bookswap#47]
User's can create easily brute-forced passwords that are any number of characters.

I made a user account and was able to make the password for it just the letter 'a'.

We Desperately need password restrictions, things like:

At BARE MINIMUM: minimum password length of 8, require a number, a capital letter, a lower case letter.

**Comment by aidielse** [comment]
Additionally, we can enforce periodic password changes to mitigate the threat of password compromise. Forcing users to change their passwords would reduce the window in which a given password can be targeted in a guessing attack. It also reduces the window in which a compromised password can be used without detection by the attacker.

I recommend forcing password changes every month, but that's just me.

**Comment by JoshuaKGoldberg** [comment]
Lol nobody is going to change their password once a month...

**Comment by aarmea** [comment]
I'd also like to add that passwords are communicated over the network in plain text, allowing anyone that's sniffing the interface to get the password. We're either going to want to use HTTPS for login, use someone else's (probably Google or Facebook) authentication, or encrypt the passwords somehow.

**Comment by jcamino** [comment]
I'm going to re-do the password system at some point unless someone else
wants to.

On Feb 17, 2014, at 22:43, Albert Armea notifications@github.com wrote:

I'd also like to add that passwords are communicated over the network in
plain text, allowing anyone that's sniffing the interface to get the
password. We're either going to want to use HTTPS for login, use someone
else's (probably Google or Facebook) authentication, or encrypt the
passwords somehow.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/Diogenesthecynic/Bookswap/issues/47#issuecomment-35349903
.

**Comment by JoshuaKGoldberg** [comment]
> re-do the password system

Please do! The login system was almost a direct copy & paste from the WebSys project, which was almost a direct copy & paste from the WebSys lab that required the hashes be kept in the same table.

> passwords over the network

If we don't have HTTPS, security will probably be terrible no matter what.

**Comment by jcamino** [comment]
Though I think Harish is doing OAth?

Sent from my iPad

On Feb 17, 2014, at 22:51, Josh Goldberg notifications@github.com wrote:

re-do the password system
Please do!

passwords over the network
If we don't have HTTPS, security will probably be terrible no matter what.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/Diogenesthecynic/Bookswap/issues/47#issuecomment-35350222
.

**Comment by JoshuaKGoldberg** [comment]
Harish is doing Facebook integration in general, you'd have to ask him how he's implementing it. Also, I'm going to implement a front-end check for password security - it won't affect the backend, and insecure passwords will still be possible to make, but it's good to have.

**Comment by jcamino** [comment]
Ok we'll work together. If we don't already, we should have unique user IDs
(SQL keys with auto increase?) and tie them to some authentication method.

Sent from my iPad

On Feb 17, 2014, at 22:53, Josh Goldberg notifications@github.com wrote:

Harish is doing Facebook integration in general, you'd have to ask him how
he's implementing it.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/Diogenesthecynic/Bookswap/issues/47#issuecomment-35350289
.

**Comment by JoshuaKGoldberg** [comment]
Great, and we do - `user_id`.

**Comment by JoshuaKGoldberg** [comment]
The original issue should be fixed in https://github.com/Diogenesthecynic/Bookswap/commit/635f0c58ffaab65ec0056387dc2275c138eb6cf8.
