### ISSUE TITLE
Application freezes when no password/name/email is entered upon creating a new account

### ISSUE THREAD

**Issue by aidielse** [JoshuaKGoldberg/Bookswap#48]
the Application gets stuck "Thinking..." when a user tries to register an account with at least one empty form field. The user should at least be given an error message that they must enter a password

**Comment by aidielse** [comment]
General note: All form validation should be done server side. Client side form validation is easily bypassable/editable/ignorable.

**Comment by JoshuaKGoldberg** [comment]
Fixed in https://github.com/Diogenesthecynic/Bookswap/commit/ac86e6f16bbb8162eaacafb193769c89c91e225e.
