### ISSUE TITLE
Separate user & entry tables on school

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/Bookswap#51]
Right now the site is only used on www.rpibookswap.com, so localization isn't important. In the future, it will be important to localize by school. The database of books should remain the same, but there should be a user table and an entry table for each school. 

This should be implemented once https://github.com/Diogenesthecynic/Bookswap/issues/50 is done

**Comment by harish** [comment]
I suggest a table of schools and a column in the users table to specify the school's ID.
