### ISSUE TITLE
Suggest imports on search with no or few results

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/Bookswap#53]
In level of difficulty:
1. If a search <~2 results, print a link to the import page
2. Make the import page take in search parameters via $_GET
3. Automatically import results when needed

Remember that 2 and 3 would require regular users be limited in how many queries they are allowed (see https://github.com/Diogenesthecynic/Bookswap/issues/23). The API is limited per day, so a single malicious or overeager user could temporarily disable imports for everybody.

**Comment by evmac** [comment]
So if the search returned no results, would it call the template of the import page and have it display there? Or would it be preferred that it called the import itself, and then re-ran the original query?

**Comment by JoshuaKGoldberg** [comment]
Hmm, probably the latter, or at the least just a link to the import page.. It's up to you.
