### ISSUE TITLE
Editing a username doesn't update the search bar

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/Bookswap#60]
The search bar says "Search BookSwap, {Username}". When you update your username, that doesn't change to reflect the new value.

**Comment by evmac** [comment]
It doesn't update at all, actually. Refreshing the page returns the old name that was originally entered.

E: Scratch that, tested on local server. It still doesn't update on the actual site, though.

**Comment by JoshuaKGoldberg** [comment]
Ah that was a mistake on my part (code typo not pushed to rpibookswap.com), should be fixed now.
