### ISSUE TITLE
Cannot offer or request books imported using ISBN-10

### ISSUE THREAD

**Issue by aarmea** [JoshuaKGoldberg/Bookswap#61]
Importing books using their ISBN-10 succeeds, but then attempting to do anything with it fails with an error of the form "No such ISBN exists".

Steps to reproduce:
1. Import a book using its ISBN-10 identifier. In my example, I'm using the [DPV Algorithms textbook](http://www.amazon.com/Algorithms-Sanjoy-Dasgupta-ebook/dp/B006Z0QR3I).
2. Attempt to buy or sell the textbook. Following my example, I get the error "No such ISBN exists: 15640322".
3. Delete the book from the database with `DELETE FROM books WHERE isbn=0073523402;`
4. Import the book again, this time using ISBN-13.
5. Attempt to buy or sell the textbook. Notice that it works this time.

**Comment by JoshuaKGoldberg** [comment]
Confirmed, interesting. The HTML printed on book pages is:
`<form class="add_entry" onsubmit="event.preventDefault(); entryAddSubmit(event, 0073523402);">...</form>`
Putting quotations around the number worked, so it must be converting `#0073523402` to `"73523402"` to `#15640322`.

**Comment by JoshuaKGoldberg** [comment]
Should be fixed in https://github.com/Diogenesthecynic/Bookswap/commit/b9c30f419bf73df461a301a1ccdb974ced6f9549.
