### ISSUE TITLE
Remove redundant database fields

### ISSUE THREAD

**Issue by aarmea** [JoshuaKGoldberg/Bookswap#63]
_Refer to the database as defined in [tests.php](https://github.com/Diogenesthecynic/Bookswap/blob/30fa07/tests.php)_

The entries table has `isbn`, `user_id`, `username`, and `bookname` fields. Since the `username` and `bookname` fields can be pulled from the `users` and `books` tables, they are redundant and should be removed.

**Comment by JoshuaKGoldberg** [comment]
+1 for foreign keys (as you defined in https://github.com/Diogenesthecynic/Bookswap/issues/64). `username` and `bookname` were added because entries typically print them, and having an extra database lookup for each would take longer. The more you can define with foreign keys, the better.
