### ISSUE TITLE
Use MySQL foreign keys

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/Bookswap#64]
As Albert said, since the isbn and user_id fields refer directly to rows in the users and books fields, they should be foreign keys to make maintaining database consistency easier.

**Comment by aarmea** [comment]
I'm really not sure what else I should be changing for this other than adding

```
FOREIGN KEY (`isbn`) REFERENCES `books`(`isbn`)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (`user_id`) REFERENCES `users`(`user_id`)
ON UPDATE CASCADE ON DELETE CASCADE
```

within the `CREATE TABLE IF NOT EXISTS entries (…)` block. Do you have any manually added logic for handling removing entries when books and/or users are removed?

**Comment by JoshuaKGoldberg** [comment]
Right now there's only user renaming: `publicEditUsername` calls `dbUsersRename` to rename the user, and `dbEntriesEditUsername` to rename the usernames in entries.
