### ISSUE TITLE
Automated test suite

### ISSUE THREAD

**Issue by aarmea** [JoshuaKGoldberg/Bookswap#66]
An automated test suite would help prevent introducing regressions and dramatically reduce testing time, which can speed up adding features. We could use something like [PHPUnit](http://phpunit.de/) running on [Travis CI](https://travis-ci.org/) to help implement this. Travis CI also has the added benefit of being able to automatically deploy to production if the latest master passes the tests.

**Comment by JoshuaKGoldberg** [comment]
+1, that's a good idea.

_(also, thanks for using the labels!)_
