### ISSUE TITLE
Password security is too strict

### ISSUE THREAD

**Issue by aidielse** [JoshuaKGoldberg/Bookswap#67]
I can't actually make a new account, I tried multiple variations of passwords but it's impossible for users to find out what the password requirements actually are.

**Comment by JoshuaKGoldberg** [comment]
Unable to reproduce, could you please post screenshots?

**Comment by aidielse** [comment]
![screen shot 2014-02-22 at 7 51 57 pm](https://f.cloud.github.com/assets/5459264/2239284/b8fdb8ae-9c24-11e3-83f1-fc799cd130bd.png)

The password that I tried to enter was Test123.

**Comment by JoshuaKGoldberg** [comment]
I was able to make a new account today. The rules from JS/index.js::sayPasswordSecurity and PHP/db_login.php::isPasswordSecure require:
- > 7 characters
- >=1 uppercase
- >=1 lowercase
- >=1 number
- >=1 symbol

**Comment by aidielse** [comment]
if the user is missing a symbol in his password for his new account, the page doesn't inform them.

**Comment by aidielse** [comment]
Also, I still can't make an account. No matter what account @rpi.edu I try, they all come up as taken.
![untitled](https://f.cloud.github.com/assets/5459264/2239366/36b718ce-9c2c-11e3-8dc3-f9a7755d1fb7.png)

**Comment by JoshuaKGoldberg** [comment]
Fixed the password problem, but still cannot reproduce the email problem on my machine (as opposed to yours).
