### ISSUE TITLE
Editing a username allows users to have non unique usernames

### ISSUE THREAD

**Issue by aidielse** [JoshuaKGoldberg/Bookswap#68]
It's super insecure for usernames to be non unique. And also it can be confusing. If a user goes to their account page to change their username, nothing checks to see if that username is already taken.

**Comment by aidielse** [comment]
![screen shot 2014-02-22 at 7 54 09 pm](https://f.cloud.github.com/assets/5459264/2239293/04e1ab7c-9c25-11e3-9053-a932a8dea6fd.png)

So yeah, It could get confusing if users can have the same username. Other users can be impersonated by simply changing your name.

**Comment by JoshuaKGoldberg** [comment]
That's a good point, there should be easy ways to distinguish between people. Facebook has a similar problem but solves it with, among other things, user histories.
