### ISSUE TITLE
No access control on subfiles/folders.

### ISSUE THREAD

**Issue by aidielse** [JoshuaKGoldberg/Bookswap#70]
Some sort of access control should be implemented so that user's can't navigate to rpibookswap.com/CSS/ and other subfolders.

**Comment by JoshuaKGoldberg** [comment]
This is very true; an .htacccess is much needed. At the very least, it should prevent access to files that aren't index.php. It would also be nice for it to change URLs too (.com/index.php?page=sample -> .com/sample)
