### ISSUE TITLE
Editing a Userame allows an attacker to perform a persistent Cross Site Scripting (XSS) attack

### ISSUE THREAD

**Issue by aidielse** [JoshuaKGoldberg/Bookswap#72]
The input for editing a username is not sanitized. I changed the username of one of my accounts to <script> alert(1)</script> and I was able to execute arbitrary scripts.

The worst part of this is that this username is now stored in the database. When another user logs on to their account, at the bottom of the page it shows who is buying/selling what. But the username "<script>alert(1)</script>" is interpreted as code.

 This means that someone could use this method to embed harmful code into the application that gets executed on every user's page.

Harmful code could potentially allow an attacker to:
- Bypass login restrictions
- Hijack Sessions
- Upload worms to users through rpibookswap
- Permanently Deface the Website
- Perform a Denial of Service Attack.

for instance, in this picture i set my username to: 
`<img src="http://static02.mediaite.com/geekosystem/uploads/2013/12/doge.jpg" />`

![screen shot 2014-02-24 at 4 59 53 pm](https://f.cloud.github.com/assets/5459264/2251661/15390cf6-9d9f-11e3-9259-2e6fb642a0fb.png)

**Comment by aidielse** [comment]
Me logged in from another account looking at the feed at the bottom of my home page:

![screen shot 2014-02-24 at 5 02 00 pm](https://f.cloud.github.com/assets/5459264/2251683/5415b4a6-9d9f-11e3-91a4-271c5decbc8d.png)

**Comment by JoshuaKGoldberg** [comment]
Much verbose, so explanation, wow.

This can be prevented by filtering the username using ArgStrict (assuming ArgStrict filters out HTML characters).

**Comment by jcamino** [comment]
Shiba username-pictures are a feature, not a bug.

Issue closed.

:P

On Mon, Feb 24, 2014 at 5:25 PM, Alucea notifications@github.com wrote:

> <
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Diogenesthecynic/Bookswap/issues/72#issuecomment-35947544
> .

## 

_Your time is limited, so don't waste it living someone else's life. Don't
be trapped by dogma - which is living with the results of other people's
thinking. Don't let the noise of other's opinions drown out your own inner
voice. And most important, have the courage to follow your heart and
intuition. They somehow already know what you truly want to become.
Everything else is secondary._

_Tribute to Steve Jobs, 1955-2011_
http://youtu.be/8rwsuXHA7RA (Here's to the crazy ones, narrated by Jobs)
http://www.youtu.be/UF8uR6Z6KLc (2005 Stanford commencement speech)

**Comment by JoshuaKGoldberg** [comment]
https://github.com/Diogenesthecynic/Bookswap/commit/016e3d93241bb960adf8f9bd5832b463d064ef2d filters using ArgLoose rather than ArgStrict; we'll have to see whether that solves the issue completely.

It also does not stop the editable components Javascript from setting the script on your local computer, though this won't affect other people (and disappears after page exit / reload).
