### ISSUE TITLE
User sign up is an annoying process

### ISSUE THREAD

**Issue by harish** [JoshuaKGoldberg/Bookswap#77]
Should specify all password requirements alongside the password field, not just when you don't fulfill one. Especially when requirements are that strict.

**Comment by JoshuaKGoldberg** [comment]
Fixed by https://github.com/Diogenesthecynic/Bookswap/commit/89bfefcad4f4e90af7273b51410d34eaabe89d0c and duplicate of https://github.com/Diogenesthecynic/Bookswap/issues/73
