### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/Bookswap#8]
Whenever an entry is placed, for each user id that has an entry of a different type on the same isbn, place a notification of the entry id in their account?

At any rate, connecting notifications to email and/or Facebook and/or text would be awesome.

**Comment by aarmea** [comment]
Are we planning on adding any other types of notifications? If not, I can simply pull notifications from the `entries` table and add a ~~`read` or `seen` field to it that's set to true once the user has seen the entry notification~~ ~~another table to keep track of who has seen what entries~~. [edit: in hindsight, this is a bit of a mess and a `notifications` table of some sort is the way to go]

If we are planning on adding other types of notifications, how many others and what are they? In this case, we probably need to add different data per type of notification (for example, new entry notifications need to know the corresponding entry), which means we want a `Notification` class and subclasses for each notification type. Depending on the number of types of notifications I'd use [single table](http://www.martinfowler.com/eaaCatalog/singleTableInheritance.html), [class table](http://martinfowler.com/eaaCatalog/classTableInheritance.html) or [concrete table](http://www.martinfowler.com/eaaCatalog/concreteTableInheritance.html) inheritance.

**Comment by JoshuaKGoldberg** [comment]
What types of notifications were you thinking of? If we do need more in the future that's a good idea.

Right now there would be entry notifications, as in when another user marks a buy/sell on a book you have a sell/buy on. That could be split into buy/sell, which would be mostly similar. The biggest difference would probably be on book quality: if you want to buy a fair book, like new sell entries are more relevant than any terrible. The opposite logic holds true for your sell entries.

You could theoretically just skip PHP and use a MySQL table for it all, if you wanted to.

**Comment by JoshuaKGoldberg** [comment]
Implemented in b7357be9e7352704c9fa9192b4c5e4e0e054b8b7, though not for Facebook.
