### ISSUE TITLE
Facebook & site logout don't mesh

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/Bookswap#84]
If you log out on Facebook via the Facebook button, it doesn't log you out of local.

If you log out of local while logged in on Facebook, it redirects you back to the main page (without logging you out of Facebook).

**Comment by harish** [comment]
Need a publicLogout function to resolve

**Comment by JoshuaKGoldberg** [comment]
Partially fixed in 30fb162c7f6afb33a729c744902bb3cfb503eac1 (though the upper "Log out" button doesn't log out of the site)
