### ISSUE TITLE
No error displayed when password is not secure enough when doing Facebook login

### ISSUE THREAD

**Issue by jcamino** [JoshuaKGoldberg/Bookswap#96]
It just fails silently. Same for non matching passwords.

![screen shot 2014-05-02 at 7 02 54 pm](https://cloud.githubusercontent.com/assets/892117/2868765/ec474202-d24d-11e3-8969-182541ffb9f9.png)

**Comment by JoshuaKGoldberg** [comment]
https://github.com/Diogenesthecynic/Bookswap/commit/ef068a224d98ec7b1eb246e8842abd55287e4b1b makes it show the status, though it doesn't fix it.

**Comment by JoshuaKGoldberg** [comment]
Correction: it's fixed. I think.
